services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 Curapets.asgi:application
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
